<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-RVFIE5L" failures="2" tests="31" name="testing_baba_test.TestingBaba_Main_Test" time="298.311" errors="0" timestamp="2022-08-16T09:36:32 IST" skipped="0">
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="clickonHome" time="5.431"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="clickonAbout" time="6.887"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="clickonCourses" time="10.441"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="validateCourses" time="10.395"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="clickonPractice" time="9.255"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="clicokonPlacement" time="5.404"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="clickonOnlineRegistration" time="14.363"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="clickonEvent" time="23.691"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="clickonContact" time="14.235"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="ValidateNewBatch" time="17.674"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="InvalidnameinRegisterNow" time="23.085"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="ValidateRegisterNow" time="25.738"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="VerifyHeading" time="4.085"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="GetDataofCourseLink" time="6.083"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="TextofEmail" time="4.089">
    <failure message="expected [Email us on
info@testingbaba.com] but found [Email us on
info@testingbaba.com]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Email us on
info@testingbaba.com] but found [Email us on
info@testingbaba.com]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testing_baba_page.TestingBaba_Main_Page.TextofEmail(TestingBaba_Main_Page.java:288)
at testing_baba_test.TestingBaba_Main_Test.TextofEmail(TestingBaba_Main_Test.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TextofEmail -->
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="Scrolldown" time="4.095"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="VerifyOurPlacementText" time="4.067"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="VerifyContentofOurPlacement" time="4.069"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="VerifyViewAll" time="4.640"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="VerifyPlacementDetail1" time="12.410"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="VerifyPlacementDetail2" time="12.442"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="VerifyPlacementDetail3" time="12.399"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="VerifyPlacementDetail4" time="12.375"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="ScrollDowntoOurAchievement" time="4.092"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="VerifyOurAchiementText" time="4.044"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="VerifyYearsofFoundation" time="8.161"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="VerifyNoOfPlacements" time="8.167"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="VerifyCeritifiedStaff" time="8.146"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="VerifyStudents" time="8.171"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="ScrollDowntoBottom" time="4.069"/>
  <system-out/>
  <testcase classname="testing_baba_test.TestingBaba_Main_Test" name="ValidateGetInTouch" time="6.108">
    <failure message="expected [Get In Touch
H-161 SECTOR-63 BSI Business Park,
Noida,India
Mail: info@testingbaba.com] but found [Get In Touch
H-161 SECTOR-63 BSI Business Park,
Noida,India
Mail: info@testingbaba.com]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Get In Touch
H-161 SECTOR-63 BSI Business Park,
Noida,India
Mail: info@testingbaba.com] but found [Get In Touch
H-161 SECTOR-63 BSI Business Park,
Noida,India
Mail: info@testingbaba.com]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testing_baba_page.TestingBaba_Main_Page.ValidateGetInTouch(TestingBaba_Main_Page.java:541)
at testing_baba_test.TestingBaba_Main_Test.ValidateGetInTouch(TestingBaba_Main_Test.java:202)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateGetInTouch -->
  <system-out/>
</testsuite> <!-- testing_baba_test.TestingBaba_Main_Test -->
